name:                eo-parser
version:             0.1.0.0
github:              "br4ch1st0chr0n3/eo-parser"
license:             BSD3
author:              "Danila Danko"
maintainer:          "br4ch1st0chr0n3@gmail.com"
copyright:           "2022 Danila Danko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/br4ch1st0chr0n3/eo-parser#readme>

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >=1.0.2 && <1.1

ghc-options:
- -Wall -fno-warn-type-defaults -O2

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- bifunctors
- bound
- containers
- deepseq
- free
- hashable
- insert-ordered-containers
- kan-extensions
- logict
- mtl
- parsers
- prettyprinter
- profunctors
- text
- transformers
- pretty-simple
- unordered-containers
- megaparsec
- scientific

library:
  source-dirs: src
  exposed-modules:
  - EOParser

executables:
  eo-parser:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eo-parser
    
tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eo-parser
    - hspec
    - QuickCheck

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
    - base
    - doctest
    - Glob
    - QuickCheck
    - template-haskell

